<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script src="https://cdn.bootcdn.net/ajax/libs/axios/0.20.0/axios.min.js"></script>
  <script>
    // new Promise((resolve, reject) => { // excutor
    //   console.log('执行excutor')
    // // 执行异步任务
    // })


    // function fn() {
    //   for (let index = 0; index < 100; index++) {
    //     //处理
    //   }
    // }
    // fn()

    // // 异步回调
    // setTimeout(() => {
    //   console.log('执行timout回调')
    // }, 1000)

    // // 需要2S  ===> 定时器回调只能在2S之后才执行
    // for (let index = 0; index < 1000000000; index++) {
    // }

    /* 
    .then()返回的promise的结果状态由什么决定?
      简单说: 由.then()指定并执行的回调函数的执行结果决定
      详细说: 
        什么情况导致promise是失败的?
          执行出错(抛异常了), 失败的reason就是抛出的错误
          返回一个失败的promise, 失败的reason就是返回的promise的reason
        什么情况导致promise是成功的?
          返回一个成功的promise, 成功的value就是返回promise的value
          返回一个非promise任务值, 也可以不返回(返回undefined), 成功的value就是返回值
    */


    new Promise((resolve, reject) => {
      // resolve(1)
      reject(2)
    }).then(value => {
      console.log('onResolved1()', value)
    }, reason => {
      console.log('onRejected1()', reason)
      // 执行出错(抛异常了)
      // throw 3
      // 返回一个失败的promise
      // return Promise.reject(4)

      // 返回一个成功的promise, 成功的value就是返回promise的value
      // return Promise.resolve(5)
      // 返回一个非promise任务值, 也可以不返回(返回undefined), 成功的value就是返回值
      // return 6

      // 注意: 如何创建一个promise但不返回, 本质上是返回undefined ==> value为undefined的成功promise
      Promise.reject(7)

    }).then(value => {
      console.log('onResolved2()', value)
    }, reason => {
      console.log('onResolved2()', reason)
    })


  </script>
</body>
</html>